//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunPublicBenefit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoNationRecord
    {
        public string ID { get; set; }
        public string DonationDate { get; set; }
        public string DonationAmout { get; set; }
    
        public virtual User1 User1 { get; set; }
        public virtual Project Project { get; set; }
    }
}
