//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunPublicBenefit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finance
    {
        public string ID { get; set; }
        public decimal PreMoney { get; set; }
        public bool IsIn { get; set; }
        public decimal MoneyL { get; set; }
        public decimal OutMoney { get; set; }
        public System.DateTime LDateTime { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
