//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunPublicBenefit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublicBenefit
    {
        public int ID { get; set; }
        public string BenefitName { get; set; }
        public string BenefitInitiator { get; set; }
        public bool IsOnLine { get; set; }
        public Nullable<System.DateTime> ApplyStartDate { get; set; }
        public string Site { get; set; }
        public System.DateTime ApplyAbortDate { get; set; }
        public int ApplyCount { get; set; }
        public string ActivityProfile { get; set; }
        public int UserID { get; set; }
        public bool ConsentApply { get; set; }
    }
}
