//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunPublicBenefit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublicBenefit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PublicBenefit()
        {
            this.PublicBenefitRecord = new HashSet<PublicBenefitRecord>();
        }
    
        public string ID { get; set; }
        public string BenefitName { get; set; }
        public bool IsOnLine { get; set; }
        public Nullable<System.DateTime> ApplyStartDate { get; set; }
        public string Site { get; set; }
        public System.DateTime ApplyAbortDate { get; set; }
        public int ApplyCount { get; set; }
        public string ActivityProfile { get; set; }
        public bool ConsentApply { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PublicBenefitRecord> PublicBenefitRecord { get; set; }
    }
}
