//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunPublicBenefit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User1()
        {
            this.Role = new HashSet<Role>();
        }
    
        public string ID { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Role> Role { get; set; }
        public virtual Project Project { get; set; }
        public virtual DoNationRecord DoNationRecord { get; set; }
        public virtual PublicBenefitRecord PublicBenefitRecord { get; set; }
        public virtual PublicBenefit PublicBenefit { get; set; }
        public virtual UserApprove UserApprove { get; set; }
    }
}
